config/routes.rb
Rails.application.routes.draw do
  

  root to: 'welcome#index'

  get '/sales', to: "sales#index"
  get '/sale/new/:id', to: "sales#newId", as: 'new_sale_id'
  get '/sales/:id', to: "sales#show", as: "sale"
  post '/sale/new', to: 'sales#new', as: 'sale_new'
  post '/sale/create', to: 'sales#create'
  post "/sales/:id", to: "sales#update", as: "update_sale" # submit my edits
  patch "/sales", to: "sales#complete", as: "complete_sale"
  delete "/sales/:id", to: "sales#destroy", as: "delete_sale"
  

  get '/product/search', to: 'products#search'
  get '/products', to: 'products#index', as: "products"
  get '/product/price', to: 'products#find', as: 'product_find'
  post '/product/price', to: 'products#find'
  post "/products", to: "products#create"
  patch "/products", to: "products#update", as: "update_product"
  delete "/products/:id", to: "products#destroy", as: "delete_product"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  post "/sign_out", to: "sessions#destroy" 



  # get '/sales/:id', to: "sales#show", as: "success"

  resources :sales
  resources :products

end


#         Prefix Verb   URI Pattern                  Controller#Action
#           root GET    /                            sale#index
#       sale_new GET    /sale/new(.:format)          sale#new
# product_search GET    /product/search(.:format)    product#search
#          sales GET    /sales(.:format)             sales#index
#                POST   /sales(.:format)             sales#create
#       new_sale GET    /sales/new(.:format)         sales#new
#      edit_sale GET    /sales/:id/edit(.:format)    sales#edit
#           sale GET    /sales/:id(.:format)         sales#show
#                PATCH  /sales/:id(.:format)         sales#update
#                PUT    /sales/:id(.:format)         sales#update
#                DELETE /sales/:id(.:format)         sales#destroy
#       products GET    /products(.:format)          products#index
#                POST   /products(.:format)          products#create
#    new_product GET    /products/new(.:format)      products#new
#   edit_product GET    /products/:id/edit(.:format) products#edit
#        product GET    /products/:id(.:format)      products#show
#                PATCH  /products/:id(.:format)      products#update
#                PUT    /products/:id(.:format)      products#update
#                DELETE /products/:id(.:format)      products#destroy

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :sales
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :require_login, only: [:index] 

  def index
    @products = Product.order(params[:sort]).paginate(:page => params[:page], :per_page => 100)
    @product = Product.new
    @carriers = @products.select(:carrier).distinct 
    @capacities = @products.select(:capacity).distinct
    @conditions = @products.select(:condition).distinct
  end

  def new
  end

  def create
    product_params = params.require(:product).permit(:model, :carrier, :capacity, :condition, :price)
    @product = Product.new product_params
    @product.save
    redirect_to products_path , flash: { success: "New Product Added!" }
  end
  def edit
    @product = Product.find(params[:id])
  end
  def update
    product_params = params.require(:product).permit(:model, :carrier, :capacity, :condition, :price, :id)
    @product = Product.find(params[:product][:id])
      if @product.update(product_params)
         redirect_to "/products", flash: { success: "Your Change Has Been Saved" }
      else
        redirect_to "/products"  
      end
  end
  def search
  	@products = Product.all
  	@models = @products.select(:model).distinct 
  	@carriers = @products.select(:carrier).distinct 
  	@capacities = @products.select(:capacity).distinct
  	conditions = @products.select(:condition).distinct
    @conditions = conditions.sort_by {|a| a.condition}.reverse
  end
  def find
  	@sale = Sale.new
  	@phone = Product.where(condition: params["product.condition"], carrier: params["product.carrier"], model: params["product.model"], capacity: params["product.capacity"])
  	price = @phone.first.price
  	redirect_to "/sale/new"
  end
  def destroy
    Product.delete(params[:id])
    redirect_to "/products", flash: { success: "Phone Deleted" }
  end 	
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/search.html.erb
<%= render 'layouts/header'%>
<br>
<br>
<br>
<br>

<div class="container">
<%= bootstrap_flash %>
	<div class="col-sm-5 drop-down-boxes">
			<!-- <img src="http://static.thetechjournal.net/wp-content/uploads/images/1110/1318091364-iphone-4s-now-available-for-preorder-1.png"> -->
			Select Model:
			
		<%= form_for :phone, url: sale_new_path, method: "POST" do |f| %>	
				<div class="option">
					<select name="product.model" class="form-control dropdown">
						<% @models.each do |model| %>
						  <option value="<%= model.model %>"><%= model.model %></option>
						<% end %>
					</select>
				</div>
			<br>
			<br>
				Select Provider:
				<div class="option">
					<select name="product.carrier" class="form-control dropdown">
					  <% @carriers.each do |carrier| %>
						  <option class="form-control" value="<%= carrier.carrier %>"><%= carrier.carrier %></option>
					  <% end %>
					</select>
				</div>
			<br>
			<br>
				Select Capacity:
			<div class="option">	 
				<select name="product.capacity" class="form-control dropdown">
				  <% @capacities.each do |capacity| %>
					  <option class="form-control" value="<%= capacity.capacity %>"><%= capacity.capacity %></option>
				  <% end %>
				</select>
			</div>	
			<br>
			<br>
				Select Condition: 
			<div class="option condition">
				<select name="product.condition" class="form-control dropdown">
				  <% @conditions.each do |condition| %>
					  <option value="<%= condition.condition %>" id="conditions"><%= condition.condition %></option>
				  <% end %>
			  	</select>

			  	<script>
			  	
			  	$( ".condition select" ).change(function() {
  					var condition = $(".condition select").val();
  					console.log(condition);
  					$(".info").empty()
  					if (condition == "fair") {

  						$(".info").append("<ul><li> Phone Functions Normally   </li><li>May Have Slight Scratches or Blemishes  </li><li>No Major Damage to Screen or Body </li></ul>"); 
  					}
  					else if (condition == "busted") {
  						$(".info").append("<ul><li> Screen or Body is Cracked </li><li> Small Parts Issues (Cameras or Buttons) </li><li>Must Power On. </li></ul>");
  					}
  					else if (condition == "pristine") {
  						$(".info").append("<ul><li> No Signs of Use</li><li>Functions Perfectly</li><li>Appears Like New</li></ul>");
  					}	
  					else {
  						$(".info").append("");
  					}	
  				});

			  	</script> 	
			</div>
			<br>
			<div class="info"></div>
			<br>
			<br>
		<%= f.submit "Get My Price", class: "btn btn-default btn-lg fa fa-linkedin fa-fw network-name"%>
		<% end %>
		<br>
		<br>
		<br>
	</div>
	<div class="col-sm-6 col-sm-offset-1">
		<div class="row">
			<div class="col-sm-3">
				<img src="http://ellisbenus.com/wp-content/uploads/2010/10/quote.png">
			</div>
			<div class="col-sm-9 quote-title">
				<h3>What People Are Saying</h3>
			</div>
		</div>	
			<div class="quote">	

				<p>I heard of this website from my daughter. I tried it and was so pleased. How many people have old devices they could sell, many I'm sure. This was a very refreshing change in how people today do business. Great job you guys. Thank you</p>
				<p>Bradley Farquhar</p>
				<br>
				<p>A first rate experience! A pre-addressed padded envelope came with my return address already on it, plus bubble wrap was included to protect the item being shipped. I was paid the same day the item was received.</p>
				<p>Steve Flynn</p>
				<br>
				<p>I would totally recommend them to my friends, it was fast and easy. Plus I received more then I thought I was going to get. Thank You Missy</p>
				<p>Cynthia Bridges</p>
			</div>	
	</div>	
</div>