config/routes.rb
Rails.application.routes.draw do
  

  root to: 'welcome#index'

  get '/sales', to: "sales#index"
  get '/sale/new/:id', to: "sales#newId", as: 'new_sale_id'
  get '/sales/:id', to: "sales#show", as: "sale"
  post '/sale/new', to: 'sales#new', as: 'sale_new'
  post '/sale/create', to: 'sales#create'
  post "/sales/:id", to: "sales#update", as: "update_sale" # submit my edits
  patch "/sales", to: "sales#complete", as: "complete_sale"
  delete "/sales/:id", to: "sales#destroy", as: "delete_sale"
  

  get '/product/search', to: 'products#search'
  get '/products', to: 'products#index', as: "products"
  get '/product/price', to: 'products#find', as: 'product_find'
  post '/product/price', to: 'products#find'
  post "/products", to: "products#create"
  patch "/products", to: "products#update", as: "update_product"
  delete "/products/:id", to: "products#destroy", as: "delete_product"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  post "/sign_out", to: "sessions#destroy" 



  # get '/sales/:id', to: "sales#show", as: "success"

  resources :sales
  resources :products

end


#         Prefix Verb   URI Pattern                  Controller#Action
#           root GET    /                            sale#index
#       sale_new GET    /sale/new(.:format)          sale#new
# product_search GET    /product/search(.:format)    product#search
#          sales GET    /sales(.:format)             sales#index
#                POST   /sales(.:format)             sales#create
#       new_sale GET    /sales/new(.:format)         sales#new
#      edit_sale GET    /sales/:id/edit(.:format)    sales#edit
#           sale GET    /sales/:id(.:format)         sales#show
#                PATCH  /sales/:id(.:format)         sales#update
#                PUT    /sales/:id(.:format)         sales#update
#                DELETE /sales/:id(.:format)         sales#destroy
#       products GET    /products(.:format)          products#index
#                POST   /products(.:format)          products#create
#    new_product GET    /products/new(.:format)      products#new
#   edit_product GET    /products/:id/edit(.:format) products#edit
#        product GET    /products/:id(.:format)      products#show
#                PATCH  /products/:id(.:format)      products#update
#                PUT    /products/:id(.:format)      products#update
#                DELETE /products/:id(.:format)      products#destroy

app/models/sale.rb
class Sale < ActiveRecord::Base
	validates :terms_of_service, acceptance: true
	# after_create :email_purchaser

end

app/controllers/sale_controller.rb
class SaleController < ApplicationController
  def index
  end
  def new
   	@sale = Sale.new
  	@phone = Product.where(condition: params["product.condition"], carrier: params["product.carrier"], model: params["product.model"], capacity: params["product.capacity"])
  	price = @phone.first.price
  end

  def create
  	@sale = Sale.new sale_params
    @sale.save
    redirect_to @sale
  end
  def show
   	@sale = Sale.find(params[:id])
  end  
  private

  def sale_params  
      params.require(:sale).permit(:first_name, :last_name, :address, :city, :state, :country, :zipcode, :phone, :email, :product_id)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :require_login, only: [:index] 

  def index
    @sales = Sale.order(params[:sort]).paginate(:page => params[:page], :per_page => 30)
    @products = Product.all
  end
  def new
  	@phone = Product.where(condition: params["product.condition"], carrier: params["product.carrier"], model: params["product.model"], capacity: params["product.capacity"])
    if @phone == []
      redirect_to '/product/search', flash: { success: "Sorry we do not buy that phone" }
    else
      redirect_to new_sale_id_path(@phone.first)
    end  
  end

  def newId
    @sale = Sale.new
    id = params[:id]
    @sale_id = Sale.last.id + 1 ##this + 1 is here because it was giving me the 
    @phone = Product.find(id)
  end

  def create
    # here be where email is submitted
    @sale = Sale.new email_params
    @sale.save
    
    render json: {"message" => "Success"}, status: 200
  end
  def complete
    @sale = Sale.find(params[:sale][:id])
    @sale.update(sale_params)
    redirect_to @sale
    

    
  end
  def show
   	@sale = Sale.find(params[:id])
    id = Sale.last[:product_id]
    @price = Product.find(id).price
    SaleMailer.purchase_receipt(@sale, @price).deliver ## this is the email to the customer
    UpdateMailer.update_notifier(@sale, @price).deliver ## this is the email to the client

  end 
  def update
    sale = Sale.find(params[:id])
    if params[:shipped]
      sale.update_attribute(:phone_shipped, DateTime.now)
    elsif params[:arrived]
      sale.update_attribute(:phone_arrived, DateTime.now)
    elsif params[:paid]
      sale.update_attribute(:sale_paid, DateTime.now)
    end  
      
    redirect_to "/sales"
  end
  def destroy
    Sale.delete(params[:id])
    redirect_to "/sales", flash: { success: "Record Deleted" }
  end 
  private

  def email_params  
      params.require(:sale).permit(:email)
  end
   def sale_params  
      params.require(:sale).permit(:first_name, :last_name, :address, :city, :state, :country, :zipcode, :phone, :product_id, :id, :mail_check, :complete_sale)
  end
end

app/helpers/sales_helper.rb
module SalesHelper
	
end

app/views/sales/new.html.erb
<br>
<br>
<br>
<br>
<div class="container">
	<h1 class="center">Your Cash Offer: <%= number_to_currency(@phone.first.price) %></h1>
  <br>
	

	
<div class="row">
<div class="col-sm-4">
  <div class="center">
    Apple <%= @phone.first.model %> <%= @phone.first.capacity %>GB<br>
    (<%= @phone.first.carrier %>)
  </div>
  <img class="img-responsive photo" align="middle" src="https://upload.wikimedia.org/wikipedia/commons/f/fa/IPhone_5.png" alt="">
</div> 
<div class="col-sm-8"> 
<h3>Save your price and get paid</h3>		
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          1. Please Enter your Email
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <%= form_for :sale, url: sale_create_path do |f| %>
         
            <%= f.email_field :email, class: "form-control", placeholder: 'Email', autofocus: true, required: true %>
          
        
        <button class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">Next</button>
          
     

      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"> 
          2. Payment Information
       </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        Please enter your paypal email if different than above?<br>

       <%= f.email_field :paypal_email, class: "form-control", placeholder: 'PayPal Email', autofocus: true, required: true %>
       If you would prefer to be mailed a check check here: <%=f.check_box :terms_of_service %><br>
       <button class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree"> Next</button> 
      
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
     
         3. Details
       
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
            

            <div class="col-sm-12">
          <div class="col-sm-12 payments">
            <div class="row">
                <%= f.text_field :first_name, class: "form-control", placeholder: 'First Name', autofocus: true, required: true %>
            </div>
          <div class="row">
            
                <%= f.text_field :last_name, class: "form-control", placeholder: 'Last Name', autofocus: true, required: true %>
          </div>
         
          <div class="row">
            
              <%= f.telephone_field :phone, type:"number", class: "form-control", placeholder: 'Phone', autofocus: true %>
           
          </div>
          <div class="row">
            
              <%= f.text_field :address, class: "form-control", placeholder: 'Address', autofocus: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-5">
              <%= f.text_field :city, class: "form-control", placeholder: 'City', autofocus: true %>
            </div>
            <div class="col-sm-7">
              <%= f.text_field :state, class: "form-control", placeholder: 'State', autofocus: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-5">
              <%= f.text_field :zipcode, type:"number", class: "form-control", placeholder: 'Zip Code', autofocus: true %>
            </div>
            <div class="col-sm-7">
              <%= f.text_field :country, class: "form-control", placeholder: 'Country', autofocus: true %>
            </div>
          </div>

          <%= f.hidden_field :product_id, :value => @phone.first.id %>
        <%=f.check_box :terms_of_service %>

        <%= f.submit "Sell my Phone", class: "btn btn-primary", id: "book-btn", type: "submit" %>  
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>

app/views/sales/newId.html.erb
<%= render 'layouts/header'%>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container">
	<h1 class="center">Your Cash Offer: <%= number_to_currency(@phone.price) %></h1>
  <br>
	

	
<div class="row">
<div class="col-sm-4">
  <div class="center">
    Apple <%= @phone.model %> <%= @phone.capacity %>GB<br>
    (<%= @phone.carrier %>)
  </div>
  <% if @phone.model == "iPhone 6" %>
  <img class="img-responsive" align="middle" src="http://www.libertywireless.com/img/iphone.png" alt="">
  <% elsif @phone.model == "iPhone 5" %>
    <img class="img-responsive photo" weigth="" align="middle" src="https://upload.wikimedia.org/wikipedia/commons/f/fa/IPhone_5.png" alt="">
  <% else %>
  <img class="img-responsive photo" align="middle" src="http://mockuphone.com/static/images/phones/iphone5c_blue_side1.png" alt="">
  <% end %>
</div> 
<div class="col-sm-8"> 
<h3>Save your price and get paid</h3>		
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          1. Please Enter your Email
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <%= form_for :sale, remote: true, url: sale_create_path, html: {id: "testing"} do |f| %>        
            <%= f.email_field :email, class: "form-control", placeholder: 'Email', autofocus: true, required: true %>
          <br><%= f.button "Next", class: "collapsed btn btn-default btn-lg fa fa-linkedin fa-fw network-name", id: "book-btn", type: "submit", role: "button", href: "#collapseTwo", :aria => {:controls=>"collapseTwo", :expanded=>"false"} %>  
          <script type="text/javascript">
            $("form#testing").on("ajax:success", function(){
              $(this).parent().parent().collapse()
              $("#collapseTwo").collapse() // fugggggggly
            })
          </script>
          <% end %>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo"> 
          2. Payment Information
       </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        Please enter your paypal email if different than above<br>
      <%= form_for @sale, method: "patch" do |f| %>

       <%= f.email_field :paypal_email, class: "form-control", placeholder: 'PayPal Email', autofocus: true%><br>

       <%=f.check_box :mail_check, {}, true, false %> Check the box if you would like us to mail you a check<br>
       <button class="collapsed btn btn-default btn-lg fa fa-linkedin fa-fw network-name" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree"> Next</button> 
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
     <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree"> 
         3. Details
       </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
        <div class="col-sm-12">
          <div class="col-sm-12 payments">
            <div class="row">
                <%= f.text_field :first_name, class: "form-control", placeholder: 'First Name', autofocus: true, required: true %>
            </div>
            <div class="row">
              
                  <%= f.text_field :last_name, class: "form-control", placeholder: 'Last Name', autofocus: true, required: true %>
            </div>
           
            <div class="row">
              
                <%= f.telephone_field :phone, type:"number", class: "form-control", placeholder: 'Phone', autofocus: true %>
             
            </div>
            <div class="row">
              
                <%= f.text_field :address, class: "form-control", placeholder: 'Address', autofocus: true, required: true %>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-5">
                <%= f.text_field :city, class: "form-control", placeholder: 'City', autofocus: true, required: true %>
              </div>
              <div class="col-sm-7">
                <%= f.text_field :state, class: "form-control", placeholder: 'State', autofocus: true, required: true %>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-5">
                <%= f.text_field :zipcode, type:"number", class: "form-control", placeholder: 'Zip Code', autofocus: true, required: true %>
              </div>
              <div class="col-sm-7">
                <%= f.text_field :country, class: "form-control", placeholder: 'Country', autofocus: true, required: true %>
              </div>
            </div>

          <%= f.hidden_field :product_id, :value => @phone.id %><br>
          <%= f.hidden_field :id, :value => @sale_id %>
          <%= f.hidden_field :complete_sale, :value => true %>
          <!-- Button trigger modal -->
          <%=f.check_box :terms_of_service, required: true  %> Agree with <a type="button" class="" data-toggle="modal" data-target="#myModal">Terms of Service</a><br> 

        <br><%= f.submit "Sell my Phone", class: "btn btn-default btn-lg fa fa-linkedin fa-fw network-name", id: "book-btn", type: "submit"%>  
        <% end %>
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Terms of Sale Agreement</h4>
              </div>
              <div class="modal-body">
                <%= render 'sales/terms' %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
</div>

app/views/sales/show.html.erb
<%= render 'layouts/header'%>
<br>
<br>
<br>
<br>
<br>
<br>
<div class="container center">
	<h1>Thank you</h1>
	Order Number: <%= @sale.id %><br><br>
	Your offer of <%= number_to_currency(@price) %> is locked in for 30 days.
	<br><br><p> You will recieve a email from us shortly with a shipping label.</p>
	<!-- https://developers.facebook.com/docs/plugins/share-button/  this is the link to the share button -->
</div>	