config/routes.rb
Rails.application.routes.draw do
  

  root to: 'welcome#index'

  get '/sales', to: "sales#index"
  get '/sale/new/:id', to: "sales#newId", as: 'new_sale_id'
  get '/sales/:id', to: "sales#show", as: "sale"
  post '/sale/new', to: 'sales#new', as: 'sale_new'
  post '/sale/create', to: 'sales#create'
  post "/sales/:id", to: "sales#update", as: "update_sale" # submit my edits
  patch "/sales", to: "sales#complete", as: "complete_sale"
  delete "/sales/:id", to: "sales#destroy", as: "delete_sale"
  

  get '/product/search', to: 'products#search'
  get '/products', to: 'products#index', as: "products"
  get '/product/price', to: 'products#find', as: 'product_find'
  post '/product/price', to: 'products#find'
  post "/products", to: "products#create"
  patch "/products", to: "products#update", as: "update_product"
  delete "/products/:id", to: "products#destroy", as: "delete_product"

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  post "/sign_out", to: "sessions#destroy" 



  # get '/sales/:id', to: "sales#show", as: "success"

  resources :sales
  resources :products

end


#         Prefix Verb   URI Pattern                  Controller#Action
#           root GET    /                            sale#index
#       sale_new GET    /sale/new(.:format)          sale#new
# product_search GET    /product/search(.:format)    product#search
#          sales GET    /sales(.:format)             sales#index
#                POST   /sales(.:format)             sales#create
#       new_sale GET    /sales/new(.:format)         sales#new
#      edit_sale GET    /sales/:id/edit(.:format)    sales#edit
#           sale GET    /sales/:id(.:format)         sales#show
#                PATCH  /sales/:id(.:format)         sales#update
#                PUT    /sales/:id(.:format)         sales#update
#                DELETE /sales/:id(.:format)         sales#destroy
#       products GET    /products(.:format)          products#index
#                POST   /products(.:format)          products#create
#    new_product GET    /products/new(.:format)      products#new
#   edit_product GET    /products/:id/edit(.:format) products#edit
#        product GET    /products/:id(.:format)      products#show
#                PATCH  /products/:id(.:format)      products#update
#                PUT    /products/:id(.:format)      products#update
#                DELETE /products/:id(.:format)      products#destroy

app/models/sale.rb
class Sale < ActiveRecord::Base
	validates :terms_of_service, acceptance: true
	# after_create :email_purchaser

end

app/controllers/sale_controller.rb
class SaleController < ApplicationController
  def index
  end
  def new
   	@sale = Sale.new
  	@phone = Product.where(condition: params["product.condition"], carrier: params["product.carrier"], model: params["product.model"], capacity: params["product.capacity"])
  	price = @phone.first.price
  end

  def create
  	@sale = Sale.new sale_params
    @sale.save
    redirect_to @sale
  end
  def show
   	@sale = Sale.find(params[:id])
  end  
  private

  def sale_params  
      params.require(:sale).permit(:first_name, :last_name, :address, :city, :state, :country, :zipcode, :phone, :email, :product_id)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :require_login, only: [:index] 

  def index
    @sales = Sale.order(params[:sort]).paginate(:page => params[:page], :per_page => 30)
    @products = Product.all
  end
  def new
  	@phone = Product.where(condition: params["product.condition"], carrier: params["product.carrier"], model: params["product.model"], capacity: params["product.capacity"])
    if @phone == []
      redirect_to '/product/search', flash: { success: "Sorry we do not buy that phone" }
    else
      redirect_to new_sale_id_path(@phone.first)
    end  
  end

  def newId
    @sale = Sale.new
    id = params[:id]
    @sale_id = Sale.last.id + 1 ##this + 1 is here because it was giving me the 
    @phone = Product.find(id)
  end

  def create
    # here be where email is submitted
    @sale = Sale.new email_params
    @sale.save
    
    render json: {"message" => "Success"}, status: 200
  end
  def complete
    @sale = Sale.find(params[:sale][:id])
    @sale.update(sale_params)
    redirect_to @sale
    

    
  end
  def show
   	@sale = Sale.find(params[:id])
    id = Sale.last[:product_id]
    @price = Product.find(id).price
    SaleMailer.purchase_receipt(@sale, @price).deliver ## this is the email to the customer
    UpdateMailer.update_notifier(@sale, @price).deliver ## this is the email to the client

  end 
  def update
    sale = Sale.find(params[:id])
    if params[:shipped]
      sale.update_attribute(:phone_shipped, DateTime.now)
    elsif params[:arrived]
      sale.update_attribute(:phone_arrived, DateTime.now)
    elsif params[:paid]
      sale.update_attribute(:sale_paid, DateTime.now)
    end  
      
    redirect_to "/sales"
  end
  def destroy
    Sale.delete(params[:id])
    redirect_to "/sales", flash: { success: "Record Deleted" }
  end 
  private

  def email_params  
      params.require(:sale).permit(:email)
  end
   def sale_params  
      params.require(:sale).permit(:first_name, :last_name, :address, :city, :state, :country, :zipcode, :phone, :product_id, :id, :mail_check, :complete_sale)
  end
end

app/helpers/sales_helper.rb
module SalesHelper
	
end

app/views/sale/index.html.erb
    <!-- Navigation -->



    <!-- Header -->
    <a name="about"></a>
    <div class="intro-header">
        <div class="container">

            <div class="row">
                <div class="col-lg-12">
                    <div class="intro-message">
                      
                        <ul class="list-inline intro-social-buttons">
                            <li>
                            
                                <%= link_to "Sell my iPhone Please", product_search_path, class: "btn btn-default btn-lg fa fa-linkedin fa-fw network-name", :method => :get%>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.container -->

    </div>
    <!-- /.intro-header -->

    <!-- Page Content -->

	<a  name="services"></a>
    <div class="content-section-a">

        <!-- <div class="container">
            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Death to the Stock Photo:<br>Special Thanks</h2>
                    <p class="lead">A special thanks to <a target="_blank" href="http://join.deathtothestockphoto.com/">Death to the Stock Photo</a> for providing the photographs that you see in this template. Visit their website to become a member.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="img/ipad.png" alt="">
                </div>
            </div>

        </div> -->
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

    <div class="content-section-b">

        <!-- <div class="container">

            <div class="row">
                <div class="col-lg-5 col-lg-offset-1 col-sm-push-6  col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">3D Device Mockups<br>by PSDCovers</h2>
                    <p class="lead">Turn your 2D designs into high quality, 3D product shots in seconds using free Photoshop actions by <a target="_blank" href="http://www.psdcovers.com/">PSDCovers</a>! Visit their website to download some of their awesome, free photoshop actions!</p>
                </div>
                <div class="col-lg-5 col-sm-pull-6  col-sm-6">
                    <img class="img-responsive" src="img/dog.png" alt="">
                </div>
            </div>

        </div> -->
        <!-- /.container -->

    </div>
    <!-- /.content-section-b -->

    <div class="content-section-a">

        <!-- <div class="container">

            <div class="row">
                <div class="col-lg-5 col-sm-6">
                    <hr class="section-heading-spacer">
                    <div class="clearfix"></div>
                    <h2 class="section-heading">Google Web Fonts and<br>Font Awesome Icons</h2>
                    <p class="lead">This template features the 'Lato' font, part of the <a target="_blank" href="http://www.google.com/fonts">Google Web Font library</a>, as well as <a target="_blank" href="http://fontawesome.io">icons from Font Awesome</a>.</p>
                </div>
                <div class="col-lg-5 col-lg-offset-2 col-sm-6">
                    <img class="img-responsive" src="img/phones.png" alt="">
                </div>
            </div>

        </div> -->
        <!-- /.container -->

    </div>
    <!-- /.content-section-a -->

	<a  name="contact"></a>
    <div class="banner">

        <div class="container">

            <!-- <div class="row">
                <div class="col-lg-6">
                    <h2>Connect to Start Bootstrap:</h2>
                </div>
                <div class="col-lg-6">
                    <ul class="list-inline banner-social-buttons">
                        <li>
                            <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                        </li>
                        <li>
                            <a href="https://github.com/IronSummitMedia/startbootstrap" class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
                        </li>
                        <li>
                            <a href="#" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">Linkedin</span></a>
                        </li>
                    </ul>
                </div>
            </div> -->

        </div>
        <!-- /.container -->

    </div>
    <!-- /.banner -->

    <!-- Footer -->
    <footer>
        <div class="container">
            <!-- <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li>
                            <a href="#">Home</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#services">Services</a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; Your Company 2014. All Rights Reserved</p>
                </div>
            </div> -->
        </div>
    </footer>